server:
  port: 18083

#配置redis
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tanhua-manage?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  redis:
    host: 10.10.20.160
    port: 6379
dubbo:
  application:
    name: tanhua-manage
  registry:
    address: zookeeper://10.10.20.160:2181
  consumer:
    check: false
#配置短信平台信息
tanhua:
  secret: 76bd425b6f29f7fcc2e0bfc286043df1
  #替换成自己的 oss存储信息
  sms:
    validateCodeTemplateCode: SMS_204761533
    signName: 传智播客
    parameterName: code
    accessKeyId: LTAI5tPQf9qCNmTUwtAm2zzc
    accessKeySecret: droBhjw5v0Go2FxSS3bk2dCNP5lsnF
  oss:
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    bucketName: mytanhua113
    url: https://mytanhua113.oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tPQf9qCNmTUwtAm2zzc
    accessKeySecret: droBhjw5v0Go2FxSS3bk2dCNP5lsnF
  face:
    appId: 24447715
    apiKey: PLuQZEvOD6dmny7WZrGZMNcz
    secretKey: gsqWgxxULsaMwOldrxXozTGWs8T7C0PK
  huanxin:
    url: http://a1.easemob.com/
    orgName: 1131210709083867
    appName: tanhua
    clientId: YXA6NNy0OjmlRXyWvBjp2VQyzA
    clientSecret: YXA6MY-bX3gZ2As5Yls5IQmg1GskqjQ
#mybaits-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_    #数据库表前缀
      id-type: auto        #数据库表主键的策略
